In [ ]:
#Extracting features from images. Computer vision is a study and design of computational artifacts that process and understand images.
#we will review some basic techniques used in computer vision to represent images in ML problems.

In [ ]:
#Extracting features from pixel intensities
#1.Let's use OCR(Optical Character Recognition) to create basic feature representations that could be used in an OCR application for recognizing
#handwritten digits. Each Pixel has intensity value between 0 and 16. White being the most intense i.e and black being the least i.e 16
#code
from sklearn import datasets
digits=datasets.load_digits()
#printing the first target value
print("First Digit",digits.target[0])
#print 8*8 matrix of images 0
print("Image matrix:",digits.images[0])
#Creating feature vector by reshaping the image matrix to 64 dimensional vector
print("Feature vector:",digits.images[0].reshape(-1,64))



First Digit 0
Image matrix: [[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]
Feature vector: [[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
  15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
   0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
   0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]]


In [ ]:
#conclusion: This representation can be effective for some basic task such as recognizing printed characters.
#However, recording the intensity of every pixel in the image produces large feature fectors and increases the space complexity.
#Moreover, learning from intensities of pixel at particular locations results in models that are sensitive to changes in scale,rotation
#and translation of images
#A model trained on our basic feature representations might not be able to recognize the same zero if it shifted in any direction,rotated
#or enlarged.