<a href="https://colab.research.google.com/github/vedantnib/Machine-Learning/blob/master/4%5DData_standardization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data Standardization
#Many estimators perform better when they are trained on standardized data sets.
#Standardized data has zero mean and unit variance.

In [ ]:
#Assume that a feature vector encode two explanatory variables. The first values of the first variable range from 0 to 1.
#The second explanatory variable ranges from 0 to 100000. 
#The second feature must be scaled closer to {0,1} for the data to have unit variance. If a feature's variance is orders of magnitude greater than
#the variances of other features, that feature may dominate the learning algorithm and prevent if from learning from other variables
#The value of an explanatory variable can be standardized by subtracting the variable's mean and dividing by variable's standard deviation.
#Data can be easily standardized using sklearn's 'scale' function:


In [ ]:
from sklearn import preprocessing
import numpy as np
X=np.array([[0.,0.,5.,13.,9.,1.],
           [0.,0.,13.,15.,10.,15.],
           [0.,3.,15.,2.,0.,11.]])
print(preprocessing.scale(X))


[[ 0.         -0.70710678 -1.38873015  0.52489066  0.59299945 -1.35873244]
 [ 0.         -0.70710678  0.46291005  0.87481777  0.81537425  1.01904933]
 [ 0.          1.41421356  0.9258201  -1.39970842 -1.4083737   0.33968311]]
