<a href="https://colab.research.google.com/github/vedantnib/Machine-Learning/blob/master/6%5DMulticlass_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/content/train.tsv',header=0,delimiter='\t')
print(df.count())


PhraseId      156060
SentenceId    156060
Phrase        156060
Sentiment     156060
dtype: int64


In [ ]:
print(df.head())
print(df['Phrase'].head(10)) #examining raw text, explanatory variable
print(df['Sentiment'].describe()) #examining the target class
#0: negative
#1: Somewhat negative
#2:neutral
#3: somewhat positive
#4: positive

   PhraseId  ...  Sentiment
0         1  ...          1
1         2  ...          2
2         3  ...          2
3         4  ...          2
4         5  ...          2

[5 rows x 4 columns]
0    A series of escapades demonstrating the adage ...
1    A series of escapades demonstrating the adage ...
2                                             A series
3                                                    A
4                                               series
5    of escapades demonstrating the adage that what...
6                                                   of
7    escapades demonstrating the adage that what is...
8                                            escapades
9    demonstrating the adage that what is good for ...
Name: Phrase, dtype: object
count    156060.000000
mean          2.063578
std           0.893832
min           0.000000
25%           2.000000
50%           2.000000
75%           3.000000
max           4.000000
Name: Sentiment, dtype: float64


In [ ]:
#examining instances of target class
print(df['Sentiment'].value_counts())
print(df['Sentiment'].value_counts()/df['Sentiment'].count())

2    79582
3    32927
1    27273
4     9206
0     7072
Name: Sentiment, dtype: int64
2    0.509945
3    0.210989
1    0.174760
4    0.058990
0    0.045316
Name: Sentiment, dtype: float64


In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model.logistic import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
def main():
  pipeline=Pipeline([
                     ('vect', TfidfVectorizer(stop_words='english')),
                     ('clf', LogisticRegression())
  ])
  parameters={
      'vect__max_df':(0.25,0.5),
      'vect__ngram_range':((1,1),(1,2)),
      'vect__use_idf':(True,False),
      'clf__C':(0.1,1,10),
  }
  X,y=df['Phrase'],df['Sentiment'].to_numpy()
  X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.5)
  grid_search=GridSearchCV(pipeline,parameters,n_jobs=3,verbose=1,scoring='accuracy')
  grid_search.fit(X_train,y_train)
  print("Best score: %0.3f" %grid_search.best_score_)
  print("Best scores parameters set: ")
  best_parameters=grid_search.best_estimator_.get_params() #The .best_estimator_ attribute is an instance of the specified model type,
  # which has the 'best' combination of given parameters from the param_grid. 
  for param_name in sorted(parameters.keys()):
    print('\t%s: %r'%(param_name,best_parameters[param_name]))
  predictions=grid_search.predict(X_test)
  print("Accuracy: ", accuracy_score(y_test,predictions))
  print("Confusion matrix: ", confusion_matrix(y_test, predictions))
  print("Recall: ", classification_report(y_test, predictions))
if __name__=='__main__':
  main()

Fitting 5 folds for each of 24 candidates, totalling 120 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:  4.3min
[Parallel(n_jobs=3)]: Done 120 out of 120 | elapsed: 11.8min finished
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Best score: 0.620
Best scores parameters set: 
	clf__C: 10
	vect__max_df: 0.25
	vect__ngram_range: (1, 2)
	vect__use_idf: False
Accuracy:  0.6292579777008843
Confusion matrix:  [[ 1051  1612   784   105    15]
 [  800  5284  6715   690    49]
 [  196  2791 33071  3601   213]
 [   19   435  6711  8121  1175]
 [    0    50   531  2437  1574]]
Recall:                precision    recall  f1-score   support

           0       0.51      0.29      0.37      3567
           1       0.52      0.39      0.45     13538
           2       0.69      0.83      0.75     39872
           3       0.54      0.49      0.52     16461
           4       0.52      0.34      0.41      4592

    accuracy                           0.63     78030
   macro avg       0.56      0.47      0.50     78030
weighted avg       0.61      0.63      0.61     78030

